name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - name: Code style checks
          linux: codestyle

        - name: Code tests
          linux: test
